Medusa Updates + plan_to_pose tolerances
UM-ARM-Lab/arm_robots pull request #90
Opened 2021-10-27 13:47 UTC by mr-mikmik

This pull request adds an argument when launching the med (med.launch) which is medusa. This argument is used to load the specific collision geometry of the setup.
It also modifies plan_to_pose to add position and orientation tolerances as an arguments for the function, rather than being fixed parameters.

2021-10-27 20:03 UTC, PeterMitrano requested changes
I assume you implemented `WSG50Gripper` correctly elsewhere.

please write out orientation_tol, ori_tol is not clear at all.

other than that looks good.

2021-10-29 16:26 UTC, mvandermerwe approved these changes
Subject to changes requested by Peter/Johnson.

2021-11-04 16:08 UTC, mr-mikmik commented
Changing arguments to `position_tol` and `orientation_tol` to be clear and consistent/symmetric.

2021-11-04 19:57 UTC, PeterMitrano approved these changes

2021-11-12 18:50 UTC, merged